import = [
    "~/.config/alacritty/themes/themes/gruvbox_material_hard.toml"
]

[cursor]
unfocused_hollow = true

[cursor.style]
blinking = "Never"

[env]
TERM = "xterm-256color"

[font]
size = 16

[font.glyph_offset]
x = 0
y = 5

[font.offset]
x = 0
y = 10

[font.normal]
family = "GeistMono Nerd Font"
style = "Regular"

[font.bold]
family = "GeistMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "GeistMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "GeistMono Nerd Font"
style = "Italic"


[scrolling]
history = 2000

[window]
decorations = "buttonless"
opacity = 1
blur = true
startup_mode = "Maximized"
dynamic_padding = true

[window.dimensions]
columns = 120
lines = 40

[window.padding]
x = 0
y = 0


